version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-west-2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building backend Docker image...
      - docker build -t ocr-testing-app-backend backend/
      - docker tag ocr-testing-app-backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ocr-testing-app-backend:latest

      - echo Building frontend Docker image...
      - docker build -t ocr-testing-app-frontend frontend/
      - docker tag ocr-testing-app-frontend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ocr-testing-app-frontend:latest

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ocr-testing-app-backend:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ocr-testing-app-frontend:latest

images:
  - "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ocr-testing-app-backend"
  - "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ocr-testing-app-frontend"
